version: '3.7'
services:
  speedtest:
    image: speedtest
    restart: always
    volumes:
      - ./data:/home/speedtest/data
    ports:
      - "3000:3000"
# TODO two services: runtest (speedtest runner), webviz (web app visualizer)
